# Generated by Django 5.1.7 on 2025-05-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('MATCHED', 'Matched'), ('NOT_MATCHED', 'Not_Matched')], default='NOT_MATCHED', max_length=12),
        ),
    ]
