# Generated by Django 4.2.20 on 2025-06-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="events_pics/")),
                ("description", models.TextField()),
                ("date", models.DateTimeField()),
                ("location", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="places_pics/")),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("description_intro", models.TextField(blank=True, null=True)),
                ("description_couples", models.TextField(blank=True, null=True)),
                ("description_history", models.TextField(blank=True, null=True)),
                ("description_outro", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
