# Generated by Django 4.2.20 on 2025-06-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="link1",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="link2",
            field=models.URLField(blank=True, null=True),
        ),
    ]
