# Generated by Django 4.2.20 on 2025-06-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_link1_event_link2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="link1",
        ),
        migrations.RemoveField(
            model_name="event",
            name="link2",
        ),
        migrations.AddField(
            model_name="place",
            name="link1",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="link2",
            field=models.URLField(blank=True, null=True),
        ),
    ]
